[2018-05-08 13:00:45,819] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:07:17,560] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:09:25,950] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:11:38,496] INFO Closing socket connection to /172.31.34.212. (kafka.network.Processor)
[2018-05-08 13:28:21,301] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:43:30,475] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 18
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:43:31,524] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 18
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 13:58:19,484] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [example-for-report,0] (kafka.server.ReplicaFetcherManager)
[2018-05-08 13:58:19,499] INFO Completed load of log example-for-report-0 with log end offset 0 (kafka.log.Log)
[2018-05-08 13:58:19,520] INFO Created log for partition [example-for-report,0] in /tmp/kafka-logs-0 with properties {segment.index.bytes -> 10485760, file.delete.delay.ms -> 60000, segment.bytes -> 536870912, flush.ms -> 9223372036854775807, delete.retention.ms -> 86400000, index.interval.bytes -> 4096, retention.bytes -> -1, cleanup.policy -> delete, segment.ms -> 604800000, max.message.bytes -> 1000012, flush.messages -> 9223372036854775807, min.cleanable.dirty.ratio -> 0.5, retention.ms -> 604800000}. (kafka.log.LogManager)
[2018-05-08 13:58:19,528] WARN Partition [example-for-report,0] on broker 0: No checkpointed highwatermark is found for partition [example-for-report,0] (kafka.cluster.Partition)
