[2018-05-08 11:04:36,269] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:06:20,415] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:13:11,701] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:17:03,182] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:18:26,399] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:22:17,252] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:25:15,420] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-08 11:25:27,905] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
