[2018-05-07 20:28:16,375] INFO Verifying properties (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,423] INFO Property broker.id is overridden to 1 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,423] INFO Property log.cleaner.enable is overridden to false (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,423] INFO Property log.dirs is overridden to /tmp/kafka-logs-1 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,423] INFO Property log.retention.check.interval.ms is overridden to 60000 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,424] INFO Property log.retention.hours is overridden to 168 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,424] INFO Property log.segment.bytes is overridden to 536870912 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,424] INFO Property num.io.threads is overridden to 8 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,424] INFO Property num.network.threads is overridden to 2 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,424] INFO Property num.partitions is overridden to 2 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,425] INFO Property port is overridden to 9091 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,425] INFO Property socket.receive.buffer.bytes is overridden to 1048576 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,425] INFO Property socket.request.max.bytes is overridden to 104857600 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,425] INFO Property socket.send.buffer.bytes is overridden to 1048576 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,425] INFO Property zookeeper.connect is overridden to 172.31.34.212:2181 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,426] INFO Property zookeeper.connection.timeout.ms is overridden to 1000000 (kafka.utils.VerifiableProperties)
[2018-05-07 20:28:16,440] INFO [Kafka Server 1], starting (kafka.server.KafkaServer)
[2018-05-07 20:28:16,442] INFO [Kafka Server 1], Connecting to zookeeper on 172.31.34.212:2181 (kafka.server.KafkaServer)
[2018-05-07 20:28:16,562] INFO Found clean shutdown file. Skipping recovery for all logs in data directory '/tmp/kafka-logs-1' (kafka.log.LogManager)
[2018-05-07 20:28:16,569] INFO Starting log cleanup with a period of 60000 ms. (kafka.log.LogManager)
[2018-05-07 20:28:16,579] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2018-05-07 20:28:16,626] INFO Awaiting socket connections on 0.0.0.0:9091. (kafka.network.Acceptor)
[2018-05-07 20:28:16,627] INFO [Socket Server on Broker 1], Started (kafka.network.SocketServer)
[2018-05-07 20:28:16,697] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2018-05-07 20:28:16,743] INFO conflict in /controller data: {"version":1,"brokerid":1,"timestamp":"1525724896709"} stored data: {"version":1,"brokerid":0,"timestamp":"1525724865423"} (kafka.utils.ZkUtils$)
[2018-05-07 20:28:16,933] INFO Registered broker 1 at path /brokers/ids/1 with address ip-172-31-34-212.us-east-2.compute.internal:9091. (kafka.utils.ZkUtils$)
[2018-05-07 20:28:16,957] INFO [Kafka Server 1], started (kafka.server.KafkaServer)
[2018-05-07 20:28:27,334] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:28:27,335] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:31:49,951] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:31:49,957] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:33:05,721] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:33:05,913] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:47:18,982] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:47:19,151] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:47:51,362] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:47:51,780] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:47:59,247] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:48:21,584] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:48:21,615] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:51:27,850] INFO Closing socket connection to /172.31.34.212. (kafka.network.Processor)
[2018-05-07 20:51:27,862] INFO 1 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
[2018-05-07 20:51:27,980] INFO New leader is 1 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
[2018-05-07 20:52:29,103] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:52:29,266] ERROR Closing socket for /172.31.34.212 because of error (kafka.network.Processor)
kafka.common.KafkaException: number of topics has value -1 which is not in the range (0,2147483647).
	at kafka.api.ApiUtils$.readIntInRange(ApiUtils.scala:85)
	at kafka.api.TopicMetadataRequest$.readFrom(TopicMetadataRequest.scala:41)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.api.RequestKeys$$anonfun$4.apply(RequestKeys.scala:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:353)
	at kafka.network.Processor.run(SocketServer.scala:245)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-07 20:52:34,983] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)
[2018-05-07 20:52:34,985] INFO [Socket Server on Broker 1], Shutting down (kafka.network.SocketServer)
[2018-05-07 20:52:34,987] INFO [Socket Server on Broker 1], Shutdown completed (kafka.network.SocketServer)
[2018-05-07 20:52:34,988] INFO [Kafka Request Handler on Broker 1], shutting down (kafka.server.KafkaRequestHandlerPool)
[2018-05-07 20:52:34,998] INFO [Kafka Request Handler on Broker 1], shut down completely (kafka.server.KafkaRequestHandlerPool)
[2018-05-07 20:52:35,359] INFO [Replica Manager on Broker 1]: Shut down (kafka.server.ReplicaManager)
[2018-05-07 20:52:35,359] INFO [ReplicaFetcherManager on broker 1] shutting down (kafka.server.ReplicaFetcherManager)
[2018-05-07 20:52:35,361] INFO [ReplicaFetcherManager on broker 1] shutdown completed (kafka.server.ReplicaFetcherManager)
[2018-05-07 20:52:35,363] INFO [Replica Manager on Broker 1]: Shutted down completely (kafka.server.ReplicaManager)
[2018-05-07 20:52:35,605] INFO [Kafka Server 1], shut down completed (kafka.server.KafkaServer)
